"""Update driver table

Revision ID: 0d686b344459
Revises: a2205a99f341
Create Date: 2025-07-06 18:41:46.823064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d686b344459'
down_revision: Union[str, Sequence[str], None] = 'a2205a99f341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('middle_name', sa.String(), nullable=True))
    op.add_column('drivers', sa.Column('license_number', sa.String(), nullable=False))
    
    driverstatus = postgresql.ENUM('active', 'inactive', 'banned', name='driverstatus')
    driverstatus.create(op.get_bind())

    op.add_column('drivers', sa.Column(
        'status',
        driverstatus,
        server_default='active',
        nullable=False
    ))    
    
    op.create_unique_constraint(None, 'drivers', ['license_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'drivers', type_='unique')
    op.drop_column('drivers', 'status')
    op.drop_column('drivers', 'license_number')
    op.drop_column('drivers', 'middle_name')
    # ### end Alembic commands ###
