"""delete stauts column in user blocking table

Revision ID: 25852f0c8ebe
Revises: d741a5ab0faa
Create Date: 2025-10-10 00:25:17.964221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25852f0c8ebe'
down_revision: Union[str, Sequence[str], None] = 'd741a5ab0faa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_drivers_last_location'), 'drivers', ['last_location'], unique=False)
    op.drop_column('users_blockings', 'status')
    op.create_unique_constraint(None, 'vehicles', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='unique')
    op.add_column('users_blockings', sa.Column('status', postgresql.ENUM('active', 'expired', name='user_blocking_status'), server_default=sa.text("'active'::user_blocking_status"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_drivers_last_location'), table_name='drivers')
    # ### end Alembic commands ###
