"""Add role for user

Revision ID: 49efce6c07a7
Revises: 08910cff655d
Create Date: 2025-06-19 19:40:08.891392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49efce6c07a7'
down_revision: Union[str, Sequence[str], None] = '08910cff655d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cities', ['id'])
    op.create_unique_constraint(None, 'drivers', ['id'])
    op.create_unique_constraint(None, 'orders', ['id'])
    op.add_column('users', sa.Column('roles', sa.ARRAY(sa.String()), nullable=True, server_default=sa.text("'{user}'")))
    op.execute("UPDATE users SET roles = '{user}' WHERE roles IS NULL")
    op.alter_column('users', 'roles', nullable=False)
    op.create_unique_constraint(None, 'users', ['id'])
    op.create_unique_constraint(None, 'vehicles', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'roles')
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_constraint(None, 'drivers', type_='unique')
    op.drop_constraint(None, 'cities', type_='unique')
    # ### end Alembic commands ###
