"""status for user and blockin user table

Revision ID: 9741b0770eec
Revises: db583ba81840
Create Date: 2025-10-09 16:58:07.502427

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9741b0770eec"
down_revision: Union[str, Sequence[str], None] = "db583ba81840"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_blockings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM("active", "expired", name="user_blocking_status"),
            server_default="active",
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )

    user_status = postgresql.ENUM("active", "blocked", "deleted", name="user_status")
    user_status.create(op.get_bind())

    op.alter_column(
        "orders",
        "price",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=True,
    )
    op.add_column(
        "users",
        sa.Column(
            "status",
            postgresql.ENUM("active", "blocked", name="user_status"),
            server_default="active",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "vehicles", type_="unique")
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "status")
    op.drop_constraint(None, "tg_bot_sessions", type_="unique")
    op.drop_constraint(None, "orders", type_="unique")
    op.alter_column(
        "orders",
        "price",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=False,
    )
    op.drop_constraint(None, "drivers", type_="unique")
    op.drop_index(op.f("ix_drivers_last_location"), table_name="drivers")
    op.drop_constraint(None, "cities", type_="unique")
    op.drop_table("users_blockings")
    # ### end Alembic commands ###
