"""add driver las location

Revision ID: a2205a99f341
Revises: 49efce6c07a7
Create Date: 2025-07-03 20:05:48.183895

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2205a99f341'
down_revision: Union[str, Sequence[str], None] = '49efce6c07a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column(
        'last_location', 
        geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326),
        nullable=True 
    ))   
    op.create_index(op.f('ix_drivers_last_location'), 'drivers', ['last_location'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drivers_last_location'), table_name='drivers')
    op.drop_index('idx_drivers_last_location', table_name='drivers', postgresql_using='gist')
    op.drop_column('drivers', 'last_location')
    # ### end Alembic commands ###
