"""added user_id column to blocking user table

Revision ID: d741a5ab0faa
Revises: 9741b0770eec
Create Date: 2025-10-10 00:16:55.468525

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d741a5ab0faa"
down_revision: Union[str, Sequence[str], None] = "9741b0770eec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "cities", ["id"])
    op.create_unique_constraint(None, "drivers", ["id"])
    op.create_unique_constraint(None, "orders", ["id"])
    op.create_unique_constraint(None, "tg_bot_sessions", ["id"])
    op.create_unique_constraint(None, "users", ["id"])
    op.add_column("users_blockings", sa.Column("user_id", sa.UUID(), nullable=False))
    op.create_unique_constraint(None, "users_blockings", ["id"])
    op.create_foreign_key(None, "users_blockings", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "vehicles", type_="unique")
    op.drop_constraint(None, "users_blockings", type_="foreignkey")
    op.drop_constraint(None, "users_blockings", type_="unique")
    op.drop_column("users_blockings", "user_id")
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "tg_bot_sessions", type_="unique")
    op.drop_constraint(None, "orders", type_="unique")
    op.drop_constraint(None, "drivers", type_="unique")
    op.drop_index(op.f("ix_drivers_last_location"), table_name="drivers")
    op.drop_constraint(None, "cities", type_="unique")
    # ### end Alembic commands ###
