"""added is_active column to blockin user table

Revision ID: feab404faeec
Revises: 25852f0c8ebe
Create Date: 2025-10-10 16:41:46.297315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feab404faeec'
down_revision: Union[str, Sequence[str], None] = '25852f0c8ebe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_blockings', sa.Column('is_active', sa.Boolean(), server_default='True', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_blockings', 'is_active')
    # ### end Alembic commands ###
