from typing import Protocol
from uuid import UUID

from app.domain.entities.order import Order


class BaseDraftOrderRepository(Protocol):
    async def create(self, order: Order) -> None: ...

    async def get_by_id(self, order_id: UUID) -> Order | None: ...

    async def get_by_customer_id(self, user_id: UUID) -> Order | None: ...

    async def update(self, order: Order) -> None: ...

    async def delete(self, order_id: UUID) -> None: ...
